//! Tool constants and descriptions for the Bevy BRP MCP server.
//!
//! This module consolidates all tool names, descriptions, and help text for the MCP server.
//! It provides a single source of truth for all tool-related constants.

// Macro to include help text files
macro_rules! include_help_text {
    ($file:expr) => {
        include_str!(concat!("../help_text/", $file))
    };
}

// Macro to define BRP methods with consistent naming
macro_rules! define_method {
    // For Bevy protocol methods (bevy/*)
    (bevy, $method:ident) => {
        paste::paste! {
            pub const [<BRP_METHOD_ $method:upper>]: &str = concat!("bevy/", stringify!($method));
            pub const [<TOOL_BEVY_ $method:upper>]: &str = concat!("bevy_", stringify!($method));
            pub const [<DESC_BEVY_ $method:upper>]: &str = include_help_text!(concat!("brp_tools/bevy_", stringify!($method), ".txt"));
        }
    };

    // For Bevy protocol methods with custom BRP path
    (bevy, $method:ident => $brp_path:expr) => {
        paste::paste! {
            pub const [<BRP_METHOD_ $method:upper>]: &str = $brp_path;
            pub const [<TOOL_BEVY_ $method:upper>]: &str = concat!("bevy_", stringify!($method));
            pub const [<DESC_BEVY_ $method:upper>]: &str = include_help_text!(concat!("brp_tools/bevy_", stringify!($method), ".txt"));
        }
    };

    // For BRP extras methods (brp_extras/*)
    (brp_extras, $method:ident) => {
        paste::paste! {
            pub const [<BRP_METHOD_EXTRAS_ $method:upper>]: &str = concat!("brp_extras/", stringify!($method));
            pub const [<TOOL_BRP_EXTRAS_ $method:upper>]: &str = concat!("brp_extras_", stringify!($method));
            pub const [<DESC_BRP_EXTRAS_ $method:upper>]: &str = include_help_text!(concat!("brp_tools/brp_extras_", stringify!($method), ".txt"));
        }
    };

    // For BRP internal tools (server-side functionality)
    (brp, $method:ident) => {
        paste::paste! {
            pub const [<TOOL_BRP_ $method:upper>]: &str = concat!("brp_", stringify!($method));
            pub const [<DESC_BRP_ $method:upper>]: &str = include_help_text!(concat!("brp_tools/brp_", stringify!($method), ".txt"));
        }
    };

    // For app management tools
    (app, $method:ident) => {
        paste::paste! {
            pub const [<TOOL_ $method:upper>]: &str = concat!("brp_", stringify!($method));
            pub const [<DESC_ $method:upper>]: &str = include_help_text!(concat!("app_tools/brp_", stringify!($method), ".txt"));
        }
    };

    // For log management tools
    (log, $method:ident) => {
        paste::paste! {
            pub const [<TOOL_ $method:upper>]: &str = concat!("brp_", stringify!($method));
            pub const [<DESC_ $method:upper>]: &str = include_help_text!(concat!("log_tools/brp_", stringify!($method), ".txt"));
        }
    };
}

// ============================================================================
// SPECIAL CONSTANTS
// ============================================================================

/// `bevy_brp_extras` prefix
pub const BRP_EXTRAS_PREFIX: &str = "brp_extras/";

// ============================================================================
// MCP TOOL NAMES AND DESCRIPTIONS - Generated by macros
// ============================================================================

// -----------------------------------------------------------------------------
// Core BRP Tools (Direct protocol methods)
// -----------------------------------------------------------------------------

// Generate tool constants for Bevy protocol methods
define_method!(bevy, list);
define_method!(bevy, get);
define_method!(bevy, destroy);
define_method!(bevy, insert);
define_method!(bevy, remove);
define_method!(bevy, list_resources);
define_method!(bevy, get_resource);
define_method!(bevy, insert_resource);
define_method!(bevy, remove_resource);
define_method!(bevy, mutate_resource);
define_method!(bevy, mutate_component);
define_method!(bevy, rpc_discover => "rpc.discover");
define_method!(bevy, query);
define_method!(bevy, spawn);
define_method!(bevy, registry_schema => "bevy/registry/schema");
define_method!(bevy, reparent);
define_method!(bevy, get_watch => "bevy/get+watch");
define_method!(bevy, list_watch => "bevy/list+watch");

// BRP execute tool (not a direct Bevy method, server-only)
define_method!(brp, execute);

// -----------------------------------------------------------------------------
// BRP Extras Tools (bevy_brp_extras plugin methods)
// -----------------------------------------------------------------------------

// Generate tool constants for BRP extras methods
define_method!(brp_extras, shutdown);
define_method!(brp_extras, screenshot);
define_method!(brp_extras, discover_format);
define_method!(brp_extras, send_keys);
define_method!(brp_extras, set_debug_mode);

// -----------------------------------------------------------------------------
// Server-Only BRP Tools (not direct protocol methods)
// -----------------------------------------------------------------------------

// Generate tool constants for BRP internal tools
define_method!(brp, status);
define_method!(brp, stop_watch);
define_method!(brp, list_active_watches);
define_method!(brp, set_debug_mode);

// -----------------------------------------------------------------------------
// Application Management Tools
// -----------------------------------------------------------------------------

// Generate tool constants for app management tools
define_method!(app, list_bevy_apps);
define_method!(app, list_bevy_examples);
define_method!(app, list_brp_apps);
define_method!(app, launch_bevy_app);
define_method!(app, launch_bevy_example);

// -----------------------------------------------------------------------------
// Log Management Tools
// -----------------------------------------------------------------------------

// Generate tool constants for log management tools
define_method!(log, list_logs);
define_method!(log, read_log);
define_method!(log, cleanup_logs);
